<?php

namespace Tests\Feature;

use Illuminate\Auth\AuthenticationException;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class ParticipateInForumTest extends TestCase
{
    use DatabaseMigrations;

    protected  $thread,$reply;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->thread = create('App\Thread');

        $this->reply = make('App\Reply');
    }

    /** @test */
    function unauthenticated_users_may_not_add_replies()
    {
        $this->withExceptionHandling()
            ->post('threads/1/replies',[])
            ->assertRedirect('/login');

    }

    /** @test */
    function an_authenticated_user_may_participate_in_forum_threads()
    {
        $this->signIn();

        $this->post($this->thread->post_path.'/replies',$this->reply->toArray());

        $this->get($this->thread->get_path)
            ->assertSee($this->reply->body);

    }

    /** @test */
    function a_reply_requires_a_body()
    {
        $this->postReply(['body'=>null])
             ->assertSessionHasErrors('body');
    }

    function postReply($overrides)
    {
        $this->withExceptionHandling()->signIn();

        $reply = make('App\Reply',$overrides);

        return $this->post($this->thread->post_path.'/replies',$reply->toArray());
    }
}
